# This is a basic workflow to help you get started with Actions

name: Deploy Contoso_University_Core

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Pack Contoso_University_Core"]
    branches: [main]
    types:
    - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: pack-solution.yml
        name: packed-solution
    - name: Import managed solution
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: https://org8177c811.crm.dynamics.com/
        user-name: ${{ secrets.USERNAME }}
        password-secret: ${{ secrets.PASSWORD }}
        solution-file: contoso_university_core_managed.zip
